### ISSUE TITLE
Bot needs to be updated for multi-program nature of FINOS

### ISSUE THREAD

**Issue by pmonks** [finos-osr/bot-github-chatops#40]
The bot needs to be updated to properly handle more than one GitHub org, seeing as FINOS uses an org per program.

**Comment by maoo** [comment]
Looking at https://github.com/Raynes/tentacles/blob/master/src/tentacles/repos.clj to understand how to change the [GitHub ChatOps code](https://github.com/finos-osr/bot-github-chatops/blob/master/src/bot_github_chatops/github.clj#L80) and return all repositories across all programs.

Interesting to notice that we already have this list that is daily updated by the [metadata-tool](http://github.com/finos/metadata-tool), which is our [activities.json](https://github.com/finos/finos.github.io/blob/master/activities.json) file.

Is it an option to read this JSON file and extract the repo list from there?

**Comment by pmonks** [comment]
The design I had in mind was to complete the work of publishing the [metadata-tool](https://github.com/finos/metadata-tool/) as a library (i.e. on Clojars), then have the GitHub Chatops bot use that library for determining the list of GitHub organisations managed by FINOS.

That's the only piece of information the bot needs from the metadata - everything else can be determined from GitHub.

And as an aside, the [Raynes version of tentacles](https://github.com/Raynes/tentacles/) was deprecated in 2016 due to the untimely death of the author.  The [Irresponsible Software Guild](https://github.com/irresponsible/) took over maintenance of some of his libraries (including [tentacles](https://github.com/irresponsible/tentacles/)), and it's that version that we use here.

**Comment by maoo** [comment]
Thanks @pmonks , I like the design you propose. I've just submitted a PR that takes the list of orgs from a `config.edn` configuration; it's not as good as it would be if integrated with our metadata-tool, but it gets the job done.

We can keep this issue open and work metadata-tool integration, but I'd like to merge this PR so we can have unlock members who want to use it. wdyt?

**Comment by pmonks** [comment]
Fixed in #44
